SELECT E.COMPANY_CODE,
       C.FOUNDER,
       COUNT(DISTINCT E.LEAD_MANAGER_CODE),
       COUNT(DISTINCT E.SENIOR_MANAGER_CODE),
       COUNT(DISTINCT E.MANAGER_CODE),
       COUNT(DISTINCT E.EMPLOYEE_CODE)
FROM EMPLOYEE AS E INNER JOIN COMPANY AS C
ON E.COMPANY_CODE = C.COMPANY_CODE
GROUP BY E.COMPANY_CODE, C.FOUNDER
ORDER BY E.COMPANY_CODE