SELECT C.HACKER_ID, 
       H.NAME, 
       COUNT(C.HACKER_ID) AS CREATED

FROM HACKERS AS H
JOIN CHALLENGES AS C
ON H.HACKER_ID = C.HACKER_ID

GROUP BY C.HACKER_ID, H.NAME
HAVING CREATED = (SELECT COUNT(C1.CHALLENGE_ID) AS CREATED1
                  FROM CHALLENGES AS C1
                  GROUP BY C1.HACKER_ID
                  ORDER BY CREATED1 DESC
                  LIMIT 1)
OR
       CREATED NOT IN (SELECT COUNT(C2.CHALLENGE_ID)
                       FROM CHALLENGES AS C2
                       GROUP BY C2.HACKER_ID
                       HAVING C.HACKER_ID != C2.HACKER_ID)

ORDER BY CREATED DESC, C.HACKER_ID